name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
      - "**/feature/**"
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python (usamos 3.11 para que instale bien duckdb/lightgbm/etc)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.11"

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # instala las dependencias "normales"
          pip install -r requirements.txt
          # instala herramientas de desarrollo
          pip install black isort pylint pytest

      # 4. isort (chequeo de import order)
      - name: Run isort (check only)
        run: |
          isort . --check-only --diff

      # 5. black (chequeo de formato)
      - name: Run black (check only)
        run: |
          black . --check --diff

      # 6. pylint (lint)
      - name: Run pylint
        run: |
          pylint src || true

      # 7. pytest (tests)
      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q
