best_params:
  objective: binary
  boosting_type: gbdt
  metric: None
  verbose: -1
  seed: 12345
  learning_rate: 0.09741574781865017
  num_leaves: 512
  max_depth: 15
  min_data_in_leaf: 1634
  feature_fraction: 0.5752738870929714
  bagging_fraction: 0.8756289603829204
  bagging_freq: 3
  min_split_gain: 0.043969760944759545
  min_sum_hessian_in_leaf: 1.3458265125574584
  lambda_l1: 5.8229758860560965e-08
  lambda_l2: 0.5047817018251073
  feature_fraction_bynode: 0.7084804181368524
  extra_trees: false
  max_bin: 448
  scale_pos_weight: 2.224279085501704
best_iteration: 999
gan_eval_best_cv: 196124000.0
gan_eval_stdv_cv: null
best_gan_eval_from_optuna: 199096000.0
train_months:
- 202101
- 202102
- 202103
test_month: 202104
drop_cols:
- lag_3_ctrx_quarter
ganancia_acierto: 780000.0
costo_estimulo: 20000.0
weight_baja2: 1.00002
weight_baja1: 1.00001
weight_continua: 1.0
binary_target_col: clase_binaria2
target_column_full: clase_ternaria
id_column: numero_de_cliente
period_column: foto_mes
feature_names:
- active_quarter
- cliente_vip
- internet
- cliente_edad
- cliente_antiguedad
- mrentabilidad
- mrentabilidad_annual
- mcomisiones
- mactivos_margen
- mpasivos_margen
- cproductos
- tcuentas
- ccuenta_corriente
- mcuenta_corriente_adicional
- mcuenta_corriente
- ccaja_ahorro
- mcaja_ahorro
- mcaja_ahorro_adicional
- mcaja_ahorro_dolares
- cdescubierto_preacordado
- mcuentas_saldo
- ctarjeta_debito
- ctarjeta_debito_transacciones
- mautoservicio
- ctarjeta_visa
- ctarjeta_visa_transacciones
- mtarjeta_visa_consumo
- ctarjeta_master
- ctarjeta_master_transacciones
- mtarjeta_master_consumo
- cprestamos_personales
- mprestamos_personales
- cprestamos_prendarios
- mprestamos_prendarios
- cprestamos_hipotecarios
- mprestamos_hipotecarios
- cplazo_fijo
- mplazo_fijo_dolares
- mplazo_fijo_pesos
- cinversion1
- minversion1_pesos
- minversion1_dolares
- cinversion2
- minversion2
- cseguro_vida
- cseguro_auto
- cseguro_vivienda
- cseguro_accidentes_personales
- ccaja_seguridad
- cpayroll_trx
- mpayroll
- mpayroll2
- cpayroll2_trx
- ccuenta_debitos_automaticos
- mcuenta_debitos_automaticos
- ctarjeta_visa_debitos_automaticos
- mttarjeta_visa_debitos_automaticos
- ctarjeta_master_debitos_automaticos
- mttarjeta_master_debitos_automaticos
- cpagodeservicios
- mpagodeservicios
- cpagomiscuentas
- mpagomiscuentas
- ccajeros_propios_descuentos
- mcajeros_propios_descuentos
- ctarjeta_visa_descuentos
- mtarjeta_visa_descuentos
- ctarjeta_master_descuentos
- mtarjeta_master_descuentos
- ccomisiones_mantenimiento
- mcomisiones_mantenimiento
- ccomisiones_otras
- mcomisiones_otras
- cforex
- cforex_buy
- mforex_buy
- cforex_sell
- mforex_sell
- ctransferencias_recibidas
- mtransferencias_recibidas
- ctransferencias_emitidas
- mtransferencias_emitidas
- cextraccion_autoservicio
- mextraccion_autoservicio
- ccheques_depositados
- mcheques_depositados
- ccheques_emitidos
- mcheques_emitidos
- ccheques_depositados_rechazados
- mcheques_depositados_rechazados
- ccheques_emitidos_rechazados
- mcheques_emitidos_rechazados
- tcallcenter
- ccallcenter_transacciones
- thomebanking
- chomebanking_transacciones
- ccajas_transacciones
- ccajas_consultas
- ccajas_depositos
- ccajas_extracciones
- ccajas_otras
- catm_trx
- matm
- catm_trx_other
- matm_other
- ctrx_quarter
- tmobile_app
- cmobile_app_trx
- Master_delinquency
- Master_status
- Master_mfinanciacion_limite
- Master_Fvencimiento
- Master_Finiciomora
- Master_msaldototal
- Master_msaldopesos
- Master_msaldodolares
- Master_mconsumospesos
- Master_mconsumosdolares
- Master_mlimitecompra
- Master_madelantopesos
- Master_madelantodolares
- Master_fultimo_cierre
- Master_mpagado
- Master_mpagospesos
- Master_mpagosdolares
- Master_fechaalta
- Master_mconsumototal
- Master_cconsumos
- Master_cadelantosefectivo
- Master_mpagominimo
- Visa_delinquency
- Visa_status
- Visa_mfinanciacion_limite
- Visa_Fvencimiento
- Visa_Finiciomora
- Visa_msaldototal
- Visa_msaldopesos
- Visa_msaldodolares
- Visa_mconsumospesos
- Visa_mconsumosdolares
- Visa_mlimitecompra
- Visa_madelantopesos
- Visa_madelantodolares
- Visa_fultimo_cierre
- Visa_mpagado
- Visa_mpagospesos
- Visa_mpagosdolares
- Visa_fechaalta
- Visa_mconsumototal
- Visa_cconsumos
- Visa_cadelantosefectivo
- Visa_mpagominimo
- foto_mes_int
- mes_idx
- tarjeta_mconsumototal_total
- tarjeta_cconsumos_total
- tarjeta_mlimitecompra_total
- lag1_mconsumo_total
- lag1_cconsumos_total
- delta_mconsumo_total
- delta_cconsumos_total
- mm_1_mconsumo_total
- mm_2_mconsumo_total
- mm_3_mconsumo_total
- mm_3_cconsumos_total
- ratio_utilizacion_tarjeta
- ratio_ticket_medio
- acm_mconsumo_total
- acm_cconsumos_total
- trend_slope_mconsumo_total
- trend_intercept_mconsumo_total
- lag1_Visa_mconsumototal
- lag1_Master_mconsumototal
- delta_Visa_mconsumototal
- delta_Master_mconsumototal
- tc_saldo_total
- lag_1_ctrx_quarter
- lag_2_ctrx_quarter
- avg_3_ctrx_quarter
- cliente_antiguedad_2
- cliente_antiguedad_3
- cliente_antiguedad_4
- cliente_antiguedad_5
- cliente_antiguedad_6
- delta_1_ctrx_quarter
- delta_2_ctrx_quarter
- ctrx_quarter_media_3
- ctrx_quarter_max_3
- ctrx_quarter_min_3
- ctrx_quarter_slope_3
- pct_drop_ctrx_quarter_1m
- flag_big_drop_activity
- flag_two_months_down
- flag_almost_inactive_now
- flag_high_utilization_tc
- flag_low_ticket_high_freq
- vol_tx_range_roll3
- vol_tx_rel_roll3
- delta_mrecibidas
- flag_income_drop
- ctrx_per_antiguedad
- flag_old_low_usage
- flag_trend_neg_consume_tc
- ticket_medio_tarjeta
- tarjeta_mconsumo_total
- tarjeta_mlimite_total
- freq_total_tx
- monto_total_tx
- mtransferencias_recibidas_1
- mtransferencias_emitidas_1
- ratio_utilizacion_tarjeta_1
- lag_ratio_utilizacion_tarjeta
- lag_ticket_medio_tarjeta
- lag_freq_total_tx
- lag_ctrx_quarter
- lag_tarjeta_mconsumo_total
- lag_monto_total_tx
- hist_max_ctrx_quarter
- hist_avg_ctrx_quarter
- hist_avg_tarjeta_mconsumo_total
- std_ctrx_quarter_3
- avg_ctrx_quarter_3
- std_mconsumo_tarjeta_3
- avg_mconsumo_tarjeta_3
- low_activity_count_3
- ratio_ingresos_gastos
- no_deposit_3m_count
- ratio_saldo_sobre_limite_tc
- flag_maxed_credit
- pct_ctrx_vs_histmax
- pct_cons_actual_vs_hist_avg
- delta_ratio_utilizacion
- delta_ticket_medio
- delta_freq_tx
- delta_ctrx_quarter
- delta_tarjeta_mconsumo_total
- delta_monto_total_tx
- ratio_cons_vs_freq
- ratio_cons_vs_ctrx
- ratio_credito_vs_total
- flag_cliente_reciente
- flag_veterano_apagado
- flag_inactividad_prolongada_3m
- cv_ctrx_quarter_3
- cv_mconsumo_tarjeta_3
n_trials: 50
n_estimators_max: 1000
nfold: 5
seed: 12345
